[package]
name = "chapter_8_problems"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measures_of_center = {path = "../measures_of_center"}
